2021-09-08 17:32:20 WARNING (SyncWorker_0) [homeassistant.loader] We found a custom integration sun2 which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant
2021-09-08 17:32:28 WARNING (MainThread) [homeassistant.components.webhook] Received message for unregistered webhook f06d1a61aa5c38a342b6db71f8743e282e529f663d9b996d12cd72ba7b7e2f35 from cloud
2021-09-08 17:32:32 WARNING (MainThread) [homeassistant.components.sensor] Entity sensor.cpu_temp (<class 'homeassistant.components.command_line.sensor.CommandSensor'>) with device_class None reports a temperature in °C which will be converted to °F. Temperature conversion for entities without correct device_class is deprecated and will be removed from Home Assistant Core 2022.3. Please update your configuration if device_class is manually configured, otherwise create a bug report at https://github.com/home-assistant/core/issues?q=is%3Aopen+is%3Aissue+label%3A%22integration%3A+command_line%22
2021-09-08 17:32:32 ERROR (MainThread) [homeassistant.components.websocket_api.http.connection] [23162035602816] Error handling message: Unknown error
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/components/websocket_api/decorators.py", line 25, in _handle_async_response
    await func(hass, connection, msg)
  File "/usr/src/homeassistant/homeassistant/components/history/__init__.py", line 175, in ws_get_list_statistic_ids
    statistic_ids = await hass.async_add_executor_job(
  File "/usr/local/lib/python3.9/concurrent/futures/thread.py", line 52, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/usr/src/homeassistant/homeassistant/components/recorder/statistics.py", line 316, in list_statistic_ids
    for platform in hass.data[DOMAIN].values():
RuntimeError: dictionary changed size during iteration
2021-09-08 17:32:33 WARNING (MainThread) [homeassistant.config_entries] Config entry 'Roku Smart Soundbar' for roku integration not ready yet: Invalid response from API: Error occurred while communicating with device; Retrying in background
2021-09-08 17:32:40 ERROR (MainThread) [homeassistant.components.snmp.sensor] Please check the details in the configuration file
2021-09-08 17:32:40 ERROR (MainThread) [homeassistant.components.snmp.sensor] Please check the details in the configuration file
2021-09-08 17:32:40 ERROR (MainThread) [homeassistant.components.snmp.sensor] Please check the details in the configuration file
2021-09-08 17:32:40 ERROR (MainThread) [homeassistant.components.snmp.sensor] Please check the details in the configuration file
2021-09-08 17:32:40 ERROR (MainThread) [homeassistant.components.snmp.sensor] Please check the details in the configuration file
2021-09-08 17:32:40 WARNING (MainThread) [homeassistant.components.sensor] Entity sensor.attictemp1_bme280_dewpoint (<class 'homeassistant.components.tasmota.sensor.TasmotaSensor'>) with device_class None reports a temperature in °C which will be converted to °F. Temperature conversion for entities without correct device_class is deprecated and will be removed from Home Assistant Core 2022.3. Please update your configuration if device_class is manually configured, otherwise create a bug report at https://github.com/home-assistant/core/issues?q=is%3Aopen+is%3Aissue+label%3A%22integration%3A+tasmota%22
2021-09-08 17:32:40 WARNING (MainThread) [homeassistant.components.sensor] Entity sensor.garagesidedoorsensor_bme280_dewpoint (<class 'homeassistant.components.tasmota.sensor.TasmotaSensor'>) with device_class None reports a temperature in °C which will be converted to °F. Temperature conversion for entities without correct device_class is deprecated and will be removed from Home Assistant Core 2022.3. Please update your configuration if device_class is manually configured, otherwise create a bug report at https://github.com/home-assistant/core/issues?q=is%3Aopen+is%3Aissue+label%3A%22integration%3A+tasmota%22
2021-09-08 17:32:40 WARNING (MainThread) [homeassistant.config_entries] Config entry '192.168.7.195' for wled integration not ready yet: Invalid response from API: Error occurred while communicating with WLED device at 192.168.7.195; Retrying in background
2021-09-08 17:33:28 WARNING (MainThread) [homeassistant.bootstrap] Waiting on integrations to complete setup: forecast_solar
2021-09-08 17:34:21 ERROR (bellows.thread_0) [bellows.uart] CRC error in frame b'9c4e24abeece698bf3c67b89f07e38a7ebcdde6f8fffc7dbd5d2698c4623a9ec763ba5ea758241984c2613b1e070381c0e07bbe5ca658a459a4d9e4f9ff7c3d9d46a35a25190482405137e' (b'0513' != b'4250')
2021-09-08 17:34:28 WARNING (MainThread) [homeassistant.bootstrap] Waiting on integrations to complete setup: forecast_solar
2021-09-08 17:34:39 WARNING (MainThread) [homeassistant.config_entries] Config entry 'Cerezo House HA' for forecast_solar integration not ready yet: Cannot connect to host 91.228.53.233:443 ssl:False [Connect call failed ('91.228.53.233', 443)]; Retrying in background
2021-09-08 17:35:14 ERROR (stream_worker) [homeassistant.components.stream.worker] Error opening stream rtsps://stream-uc2-delta.dropcam.com:443/sdm_live_stream/CiQA2vuxr_j4cFVPhxroR-Pbi7EZlNtporQ4CnRIW1NZwIq2WfYScQBQBG8tDgVlqAGMwJ-Ah9FY5fmd_MYLoqJYX5znlpnOJ1-K9EFGqRVed-MCwZOViWwWw8f4Ln_HPgKVeMpkyNOzXwjMXTxBrqT6lyrsshJgJAs2T6Pt6LU4tSdXF3-XyOGzN2JSWsyEffCYzefGxAL9?auth=g.0.eyJraWQiOiIyMzhiNTUxZmMyM2EyM2Y4M2E2ZTE3MmJjZTg0YmU3ZjgxMzAzMmM4IiwiYWxnIjoiUlMyNTYifQ.eyJpc3MiOiJuZXN0LXNlY3VyaXR5LWF1dGhwcm94eSIsInN1YiI6Im5lc3RfaWQ6bmVzdC1waG9lbml4LXByb2Q6MjEyMTgxNDEiLCJwb2wiOiIzcC1vYXV0aC1zY29wZS1BUElfU0RNX1NFUlZJQ0UtY2xpZW50LTIwMjQyNzMxODczNS1qNXQ5bWMyMzZqaG85YXMycWY0dTZxY3NmYW1kaGJ0ci5hcHBzLmdvb2dsZXVzZXJjb250ZW50LmNvbSIsImV4cCI6MTYzMTE0Nzk4Mn0.nBwiyOH9Lshq-I_MSw4N-jdzgbU_fw3ScyKuOX-wh1if79DyLBad2i88ytYcxthN8EVCOFAybsffDKssMJ4VPs4rrLI3R5hz9skldMwQ3wdTaXUthbpmTbHBjjdpDpmh0JicLWfkV76vL_BH_Ir3ZqFXJnewFl70-Cc6UEmWNjUHr1m3v6PZRR-nWoazw_mGEmNqXz-An8PRBV9yB6WzFxTHpxQb2G5y1KD2E1W_tmapzJymMeuMsP3s8l2wR3YDn1GP7-Kle6LTJiu5UN5rMvPdVwQ4l_F7NDVZpUZhr9_T4fJsOqrEvCH9I903LnJLBAo3JFzp9CPv-a04qFIS3w
2021-09-08 17:36:39 ERROR (MainThread) [homeassistant.components.template.template_entity] TemplateError('TypeError: unsupported operand type(s) for -: 'NoneType' and 'int'') while processing template 'Template("{{ (state_attr('sensor.firewall_wan_in_stats','change_rate')|float*8*(state_attr('sensor.firewall_wan_in_stats', 'sampling_size')-1)/1000000)|round(2) }}")' for attribute '_attr_native_value' in entity 'sensor.firewall_internet_in_mbps'
2021-09-08 17:36:39 ERROR (MainThread) [homeassistant.components.template.template_entity] TemplateError('TypeError: unsupported operand type(s) for -: 'NoneType' and 'int'') while processing template 'Template("{{ (state_attr('sensor.firewall_wan_out_stats','change_rate')|float*8*(state_attr('sensor.firewall_wan_out_stats', 'sampling_size')-1)/1000000)|round(2) }}")' for attribute '_attr_native_value' in entity 'sensor.firewall_internet_out_mbps'
2021-09-08 17:36:46 ERROR (MainThread) [homeassistant.components.template.cover] Received invalid cover is_on state: unavailable. Expected: open, opening, closed, closing, true, false
2021-09-08 17:36:48 ERROR (MainThread) [iotawattpy.connection] Err: 
2021-09-08 17:36:48 ERROR (MainThread) [homeassistant.components.iotawatt.coordinator] Unexpected error fetching 192.168.20.195 data: 'NoneType' object has no attribute 'text'
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 187, in _async_refresh
    self.data = await self._async_update_data()
  File "/usr/src/homeassistant/homeassistant/components/iotawatt/coordinator.py", line 55, in _async_update_data
    await self.api.update()
  File "/usr/local/lib/python3.9/site-packages/iotawattpy/iotawatt.py", line 66, in update
    await self._refreshSensors(timespan)
  File "/usr/local/lib/python3.9/site-packages/iotawattpy/iotawatt.py", line 169, in _refreshSensors
    values = json.loads(response.text)
AttributeError: 'NoneType' object has no attribute 'text'
2021-09-08 17:36:48 WARNING (MainThread) [homeassistant.components.template.template_entity] Template loop detected while processing event: <Event state_changed[L]: entity_id=sensor.sensor_count, old_state=<state sensor.sensor_count=453; friendly_name=Number of Sensors @ 2021-09-08T17:36:44.661038-07:00>, new_state=<state sensor.sensor_count=473; friendly_name=Number of Sensors @ 2021-09-08T17:36:46.882601-07:00>>, skipping template render for Template[{{ states.sensor | rejectattr('state', 'eq', 'unavailable') | list | count }}]
2021-09-08 17:36:49 WARNING (MainThread) [homeassistant.components.sensor] Entity sensor.cpu_temp (<class 'homeassistant.components.command_line.sensor.CommandSensor'>) with device_class None reports a temperature in °C which will be converted to °F. Temperature conversion for entities without correct device_class is deprecated and will be removed from Home Assistant Core 2022.3. Please update your configuration if device_class is manually configured, otherwise create a bug report at https://github.com/home-assistant/core/issues?q=is%3Aopen+is%3Aissue+label%3A%22integration%3A+command_line%22
2021-09-08 17:37:27 ERROR (MainThread) [homeassistant] Error doing job: Future exception was never retrieved
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/concurrent/futures/thread.py", line 52, in run
    result = self.fn(*self.args, **self.kwargs)
TypeError: update() takes 1 positional argument but 2 were given
